import { Layout } from "@/components/Main";
import "@/styles/globals.css";
// import "@/styles/bootstrap.css"
import "@/styles/ui.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
